const BIBLE_HUB_BOOK_PATHS = {
  'Genesis': 'genesis',
  'Exodus': 'exodus',
  'Leviticus': 'leviticus',
  'Numbers': 'numbers',
  'Deuteronomy': 'deuteronomy',
  'Joshua': 'joshua',
  'Judges': 'judges',
  'Ruth': 'ruth',
  '1 Samuel': '1_samuel',
  '2 Samuel': '2_samuel',
  '1 Kings': '1_kings',
  '2 Kings': '2_kings',
  '1 Chronicles': '1_chronicles',
  '2 Chronicles': '2_chronicles',
  'Ezra': 'ezra',
  'Nehemiah': 'nehemiah',
  'Esther': 'esther',
  'Job': 'job',
  'Psalms': 'psalms',
  'Proverbs': 'proverbs',
  'Ecclesiastes': 'ecclesiastes',
  'Song of Solomon': 'songs',
  'Isaiah': 'isaiah',
  'Jeremiah': 'jeremiah',
  'Lamentations': 'lamentations',
  'Ezekiel': 'ezekiel',
  'Daniel': 'daniel',
  'Hosea': 'hosea',
  'Joel': 'joel',
  'Amos': 'amos',
  'Obadiah': 'obadiah',
  'Jonah': 'jonah',
  'Micah': 'micah',
  'Nahum': 'nahum',
  'Habakkuk': 'habakkuk',
  'Zephaniah': 'zephaniah',
  'Haggai': 'haggai',
  'Zechariah': 'zechariah',
  'Malachi': 'malachi',
  'Matthew': 'matthew',
  'Mark': 'mark',
  'Luke': 'luke',
  'John': 'john',
  'Acts': 'acts',
  'Romans': 'romans',
  '1 Corinthians': '1_corinthians',
  '2 Corinthians': '2_corinthians',
  'Galatians': 'galatians',
  'Ephesians': 'ephesians',
  'Philippians': 'philippians',
  'Colossians': 'colossians',
  '1 Thessalonians': '1_thessalonians',
  '2 Thessalonians': '2_thessalonians',
  '1 Timothy': '1_timothy',
  '2 Timothy': '2_timothy',
  'Titus': 'titus',
  'Philemon': 'philemon',
  'Hebrews': 'hebrews',
  'James': 'james',
  '1 Peter': '1_peter',
  '2 Peter': '2_peter',
  '1 John': '1_john',
  '2 John': '2_john',
  '3 John': '3_john',
  'Jude': 'jude',
  'Revelation': 'revelation'
};

export function getBibleHubVerseUrl(book, chapter, verse) {
  const bookPath = BIBLE_HUB_BOOK_PATHS[book];
  if (!bookPath) return null;
  return `https://biblehub.com/study/${bookPath}/${chapter}-${verse}.htm`;
}